import { Habit, Task, Note, JournalEntry, CalendarEvent } from './types';
import { getToday } from './utils';

// Date helpers for demo data generation
const getRelativeDateStr = (offsetDays: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

const today = getToday();

// Helper to generate realistic completion dates over past 30 days
const generateCompletionDates = (probability: number, maxDays = 30): string[] => {
  const dates: string[] = [];
  for (let i = 0; i < maxDays; i++) {
    const dStr = getRelativeDateStr(-i);
    // Deterministic pseudo-random selection based on index & probability
    if ((i * 7 + Math.round(probability * 10)) % 10 < probability * 10) {
      dates.push(dStr);
    }
  }
  if (!dates.includes(today) && probability > 0.6) {
    dates.push(today);
  }
  return dates.sort();
};

export const DEMO_HABITS: Habit[] = [
  {
    id: 'demo-h1',
    name: 'DSA Practice',
    icon: '💻',
    color: '#4C6A73',
    createdAt: getRelativeDateStr(-30),
    completedDates: generateCompletionDates(0.85),
    isDemo: true,
  },
  {
    id: 'demo-h2',
    name: 'Morning Exercise',
    icon: '🏃‍♀️',
    color: '#6B7F4E',
    createdAt: getRelativeDateStr(-30),
    completedDates: generateCompletionDates(0.75),
    isDemo: true,
  },
  {
    id: 'demo-h3',
    name: 'Read 10 Pages',
    icon: '📚',
    color: '#4C6A73',
    createdAt: getRelativeDateStr(-30),
    completedDates: generateCompletionDates(0.65),
    isDemo: true,
  },
  {
    id: 'demo-h4',
    name: 'Drink 2L Water',
    icon: '💧',
    color: '#A2B5A0',
    createdAt: getRelativeDateStr(-30),
    completedDates: generateCompletionDates(0.9),
    isDemo: true,
  },
  {
    id: 'demo-h5',
    name: 'Project Development',
    icon: '🚀',
    color: '#1F3D2E',
    createdAt: getRelativeDateStr(-30),
    completedDates: generateCompletionDates(0.8),
    isDemo: true,
  },
  {
    id: 'demo-h6',
    name: 'Java Practice',
    icon: '☕',
    color: '#DCC8A3',
    createdAt: getRelativeDateStr(-30),
    completedDates: generateCompletionDates(0.7),
    isDemo: true,
  },
  {
    id: 'demo-h7',
    name: 'Communication Practice',
    icon: '🗣️',
    color: '#5A443A',
    createdAt: getRelativeDateStr(-30),
    completedDates: generateCompletionDates(0.6),
    isDemo: true,
  },
  {
    id: 'demo-h8',
    name: 'LinkedIn Activity',
    icon: '💼',
    color: '#4C6A73',
    createdAt: getRelativeDateStr(-30),
    completedDates: generateCompletionDates(0.55),
    isDemo: true,
  },
  {
    id: 'demo-h9',
    name: 'GitHub Contribution',
    icon: '🐙',
    color: '#1F3D2E',
    createdAt: getRelativeDateStr(-30),
    completedDates: generateCompletionDates(0.8),
    isDemo: true,
  },
  {
    id: 'demo-h10',
    name: 'Coding Practice',
    icon: '⚡',
    color: '#6B7F4E',
    createdAt: getRelativeDateStr(-30),
    completedDates: generateCompletionDates(0.75),
    isDemo: true,
  },
  {
    id: 'demo-h11',
    name: 'Meditation',
    icon: '🧘‍♀️',
    color: '#A2B5A0',
    createdAt: getRelativeDateStr(-30),
    completedDates: generateCompletionDates(0.65),
    isDemo: true,
  },
  {
    id: 'demo-h12',
    name: 'Early Wake Up',
    icon: '🌅',
    color: '#DCC8A3',
    createdAt: getRelativeDateStr(-30),
    completedDates: generateCompletionDates(0.5),
    isDemo: true,
  },
  {
    id: 'demo-h13',
    name: 'English Speaking',
    icon: '🗣️',
    color: '#5A443A',
    createdAt: getRelativeDateStr(-30),
    completedDates: generateCompletionDates(0.6),
    isDemo: true,
  },
  {
    id: 'demo-h14',
    name: 'Portfolio Work',
    icon: '🎨',
    color: '#4C6A73',
    createdAt: getRelativeDateStr(-30),
    completedDates: generateCompletionDates(0.7),
    isDemo: true,
  },
  {
    id: 'demo-h15',
    name: 'Problem Solving',
    icon: '🧠',
    color: '#6B7F4E',
    createdAt: getRelativeDateStr(-30),
    completedDates: generateCompletionDates(0.8),
    isDemo: true,
  },
];

export const DEMO_TASKS: Task[] = [
  {
    id: 'demo-t1',
    title: 'Complete Array Problems',
    description: 'Solve 4 LeetCode Medium problems on Two Pointers & Sliding Window.',
    priority: 'high',
    status: 'done',
    category: 'Education',
    dueDate: today,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-t2',
    title: 'Finish LifeOS Dashboard',
    description: 'Refine responsive bento grid layout and real-time state listeners.',
    priority: 'high',
    status: 'done',
    category: 'Work',
    dueDate: today,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-t3',
    title: 'Review System Architecture',
    description: 'Ensure central state propagation across all widgets and pages.',
    priority: 'high',
    status: 'done',
    category: 'Work',
    dueDate: today,
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    completedAt: new Date(Date.now() - 86400000).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-t4',
    title: 'Build Calendar Integration',
    description: 'Add Google Calendar-style month/week/day/agenda views.',
    priority: 'high',
    status: 'in-progress',
    category: 'Work',
    dueDate: today,
    createdAt: new Date().toISOString(),
    completedAt: null,
    isDemo: true,
  },
  {
    id: 'demo-t5',
    title: 'Update Portfolio',
    description: 'Add new full-stack projects and detailed architectural case studies.',
    priority: 'medium',
    status: 'todo',
    category: 'Personal',
    dueDate: getRelativeDateStr(1),
    createdAt: new Date().toISOString(),
    completedAt: null,
    isDemo: true,
  },
  {
    id: 'demo-t6',
    title: 'Push Project to GitHub',
    description: 'Commit final polished source code and push to main branch.',
    priority: 'high',
    status: 'todo',
    category: 'Work',
    dueDate: getRelativeDateStr(1),
    createdAt: new Date().toISOString(),
    completedAt: null,
    isDemo: true,
  },
  {
    id: 'demo-t7',
    title: 'Practice Java DSA',
    description: 'Implement Binary Trees & Graph traversal algorithms in Java.',
    priority: 'high',
    status: 'todo',
    category: 'Education',
    dueDate: getRelativeDateStr(-1),
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    completedAt: null,
    isDemo: true,
  },
  {
    id: 'demo-t8',
    title: 'Complete React Revision',
    description: 'Review custom hooks, Context API, and state optimization patterns.',
    priority: 'medium',
    status: 'done',
    category: 'Education',
    dueDate: getRelativeDateStr(-2),
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    completedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-t9',
    title: 'Prepare Resume',
    description: 'Format full-stack projects section and highlight tech stack competencies.',
    priority: 'high',
    status: 'todo',
    category: 'Personal',
    dueDate: getRelativeDateStr(2),
    createdAt: new Date().toISOString(),
    completedAt: null,
    isDemo: true,
  },
  {
    id: 'demo-t10',
    title: 'Review MongoDB Concepts',
    description: 'Study indexing, aggregation pipelines, and schema validation.',
    priority: 'low',
    status: 'todo',
    category: 'Education',
    dueDate: getRelativeDateStr(3),
    createdAt: new Date().toISOString(),
    completedAt: null,
    isDemo: true,
  },
  {
    id: 'demo-t11',
    title: 'Build AI Assistant Flow',
    description: 'Optimize response parsing and rapid action execution.',
    priority: 'high',
    status: 'done',
    category: 'Work',
    dueDate: today,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-t12',
    title: 'Fix Responsive UI',
    description: 'Audit mobile viewports across Habits, Tasks, and Analytics.',
    priority: 'medium',
    status: 'in-progress',
    category: 'Work',
    dueDate: today,
    createdAt: new Date().toISOString(),
    completedAt: null,
    isDemo: true,
  },
  {
    id: 'demo-t13',
    title: 'Study Aptitude',
    description: 'Solve 20 Quantitative Reasoning questions on speed and distance.',
    priority: 'low',
    status: 'todo',
    category: 'Education',
    dueDate: getRelativeDateStr(4),
    createdAt: new Date().toISOString(),
    completedAt: null,
    isDemo: true,
  },
  {
    id: 'demo-t14',
    title: 'Complete LinkedIn Profile',
    description: 'Update headline, summary, and project featured links.',
    priority: 'low',
    status: 'done',
    category: 'Personal',
    dueDate: getRelativeDateStr(-3),
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    completedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-t15',
    title: 'Prepare Mock Interview',
    description: 'Review common System Design questions and STAR method answers.',
    priority: 'high',
    status: 'todo',
    category: 'Personal',
    dueDate: getRelativeDateStr(5),
    createdAt: new Date().toISOString(),
    completedAt: null,
    isDemo: true,
  },
];

export const DEMO_JOURNAL: JournalEntry[] = [
  {
    id: 'demo-j1',
    date: today,
    mood: '😄',
    content: 'Productive Coding Day! Connected all modules to the unified data layer and streamlined state management.',
    gratitude: ['Good health', 'Clean code architecture', 'Clear mental focus'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-j2',
    date: getRelativeDateStr(-1),
    mood: '😊',
    content: 'Learning Progress: Solved 3 LeetCode Medium problems on Sliding Window. Made steady progress on the frontend.',
    gratitude: ['Continuous learning', 'Great coffee', 'Problem solving'],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-j3',
    date: getRelativeDateStr(-2),
    mood: '😄',
    content: 'DSA Practice Reflection: Reviewed binary search boundary conditions. Solved edge cases cleanly.',
    gratitude: ['Mentorship', 'Good sleep', 'Productive morning'],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-j4',
    date: getRelativeDateStr(-3),
    mood: '😊',
    content: 'Project Milestone: Finished the responsive bento layout for Analytics. Charts look clean.',
    gratitude: ['Creative inspiration', 'Fresh tea', 'Family support'],
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-j5',
    date: getRelativeDateStr(-4),
    mood: '😐',
    content: 'Difficult but Useful Day: Dealt with tricky async state sync, but figured out the root cause.',
    gratitude: ['Patience', 'Restful evening', 'Good books'],
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-j6',
    date: getRelativeDateStr(-5),
    mood: '😊',
    content: 'Weekend Reset: Took a morning walk, organized workspace, and planned upcoming learning goals.',
    gratitude: ['Clear goals', 'Steady focus', 'Cool weather'],
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-j7',
    date: getRelativeDateStr(-6),
    mood: '😄',
    content: 'Small Wins: Completed morning workout and hit 100% daily habit targets.',
    gratitude: ['Physical energy', 'Clean space', 'High motivation'],
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-j8',
    date: getRelativeDateStr(-7),
    mood: '😊',
    content: 'Career Planning: Refined full-stack portfolio section. Outlined technical case studies.',
    gratitude: ['Ambition', 'Networking', 'Learning resources'],
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-j9',
    date: getRelativeDateStr(-8),
    mood: '😄',
    content: 'Focus Day: Completed 4 Pomodoro blocks on LifeOS UI Polish without distractions.',
    gratitude: ['Deep work', 'Calm environment', 'Productivity'],
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-j10',
    date: getRelativeDateStr(-9),
    mood: '😊',
    content: 'Learning React: Built custom state hook for action dispatching.',
    gratitude: ['Modern JS', 'Clean API designs', 'Great documentation'],
    createdAt: new Date(Date.now() - 86400000 * 9).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 9).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-j11',
    date: getRelativeDateStr(-10),
    mood: '😄',
    content: 'Portfolio Progress: Deployed live project links and verified mobile responsiveness.',
    gratitude: ['Feedback', 'Deployment speed', 'Web Vitals'],
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-j12',
    date: getRelativeDateStr(-11),
    mood: '😊',
    content: 'New Ideas: Sketched initial concept for AI-driven habit coaching.',
    gratitude: ['Innovation', 'System thinking', 'Clear mind'],
    createdAt: new Date(Date.now() - 86400000 * 11).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 11).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-j13',
    date: getRelativeDateStr(-12),
    mood: '😐',
    content: 'Challenging Day: Debugged complex recursion issue. Took time but learned a lot.',
    gratitude: ['Perseverance', 'Rest', 'Patience'],
    createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-j14',
    date: getRelativeDateStr(-13),
    mood: '😄',
    content: 'Good Study Session: Covered 2 chapters on System Architecture and caching.',
    gratitude: ['Books', 'Fast comprehension', 'Energy'],
    createdAt: new Date(Date.now() - 86400000 * 13).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 13).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-j15',
    date: getRelativeDateStr(-14),
    mood: '😊',
    content: 'Weekly Reflection: Reviewed weekly progress. Achieved 88% overall task completion rate.',
    gratitude: ['Weekly consistency', 'Health', 'Future growth'],
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    isDemo: true,
  },
];

export const DEMO_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 'demo-e1',
    title: 'DSA Study Session',
    description: 'Solve LeetCode Medium array & matrix problems.',
    date: today,
    startTime: '09:00',
    endTime: '10:30',
    color: '#4C6A73',
    createdAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-e2',
    title: 'Project Deep Work',
    description: 'Focus block on LifeOS feature polish.',
    date: today,
    startTime: '14:00',
    endTime: '16:00',
    color: '#6B7F4E',
    createdAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-e3',
    title: 'System Architecture Review',
    description: 'Review state propagation and API contracts.',
    date: getRelativeDateStr(1),
    startTime: '11:00',
    endTime: '12:00',
    color: '#1F3D2E',
    createdAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-e4',
    title: 'Gym / Exercise',
    description: 'Upper body workout & cardio.',
    date: getRelativeDateStr(1),
    startTime: '17:30',
    endTime: '18:45',
    color: '#6B7F4E',
    createdAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-e5',
    title: 'Portfolio Work',
    description: 'Add project screenshots and writeup.',
    date: getRelativeDateStr(2),
    startTime: '10:00',
    endTime: '12:00',
    color: '#DCC8A3',
    createdAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-e6',
    title: 'Mock Interview',
    description: 'Practice system design questions.',
    date: getRelativeDateStr(2),
    startTime: '15:00',
    endTime: '16:00',
    color: '#5A443A',
    createdAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-e7',
    title: 'Java Practice',
    description: 'Collections framework & Stream API.',
    date: getRelativeDateStr(3),
    startTime: '09:30',
    endTime: '11:00',
    color: '#4C6A73',
    createdAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-e8',
    title: 'React Learning',
    description: 'Deep dive into server components & Turbopack.',
    date: getRelativeDateStr(3),
    startTime: '14:00',
    endTime: '15:30',
    color: '#6B7F4E',
    createdAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-e9',
    title: 'GitHub Update',
    description: 'Push commits and update README.',
    date: getRelativeDateStr(4),
    startTime: '16:30',
    endTime: '17:30',
    color: '#1F3D2E',
    createdAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-e10',
    title: 'Resume Review',
    description: 'Format resume for software engineering roles.',
    date: getRelativeDateStr(5),
    startTime: '11:00',
    endTime: '12:00',
    color: '#A2B5A0',
    createdAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-e11',
    title: 'Aptitude Practice',
    description: 'Quantitative aptitude problem sets.',
    date: getRelativeDateStr(5),
    startTime: '18:00',
    endTime: '19:00',
    color: '#DCC8A3',
    createdAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-e12',
    title: 'Communication Practice',
    description: 'Public speaking & presentation practice.',
    date: getRelativeDateStr(6),
    startTime: '10:00',
    endTime: '11:00',
    color: '#5A443A',
    createdAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-e13',
    title: 'Weekly Planning',
    description: 'Set goals and review task schedule for next week.',
    date: getRelativeDateStr(7),
    startTime: '11:00',
    endTime: '12:00',
    color: '#4C6A73',
    createdAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-e14',
    title: 'LifeOS Development',
    description: 'Feature addition & performance audit.',
    date: getRelativeDateStr(7),
    startTime: '15:00',
    endTime: '17:00',
    color: '#6B7F4E',
    createdAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-e15',
    title: 'Reading Session',
    description: 'Read 20 pages of technical architecture book.',
    date: getRelativeDateStr(8),
    startTime: '20:00',
    endTime: '21:00',
    color: '#A2B5A0',
    createdAt: new Date().toISOString(),
    isDemo: true,
  },
];

export const DEMO_NOTES: Note[] = [
  {
    id: 'demo-n1',
    title: 'DSA Notes',
    content: 'Key concepts:\n- Two Pointers for sorted arrays\n- Sliding Window for subarray sums\n- Fast & Slow pointers for cycle detection.',
    folder: 'Study',
    color: '#4C6A73',
    isPinned: true,
    tags: ['dsa', 'algorithms'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-n2',
    title: 'React Concepts',
    content: '1. Custom Hooks for reusable logic\n2. Context API for global state\n3. React.memo & useMemo for rendering optimization.',
    folder: 'Tech',
    color: '#6B7F4E',
    isPinned: true,
    tags: ['react', 'frontend'],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-n3',
    title: 'Java Notes',
    content: 'Core Java Topics:\n- OOPs principles (Polymorphism, Inheritance, Encapsulation)\n- Collections Framework (HashMap, ArrayList, PriorityQueue)\n- Stream API & Lambdas.',
    folder: 'Study',
    color: '#DCC8A3',
    isPinned: false,
    tags: ['java', 'backend'],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-n4',
    title: 'MongoDB Notes',
    content: 'Aggregation Framework:\n- $match, $group, $sort pipeline stages\n- Compound Indexing for query speed\n- Mongoose schema population.',
    folder: 'Tech',
    color: '#1F3D2E',
    isPinned: false,
    tags: ['mongodb', 'database'],
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-n5',
    title: 'Project Ideas',
    content: 'Full-stack application ideas:\n- LifeOS (All-in-one productivity suite)\n- AI Code Reviewer Bot\n- Distributed Task Queue System.',
    folder: 'Ideas',
    color: '#5A443A',
    isPinned: true,
    tags: ['projects', 'ideas'],
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-n6',
    title: 'Interview Questions',
    content: '1. Describe a difficult technical bug and how you solved it.\n2. How do you optimize API latency?\n3. Explain state management tradeoffs.',
    folder: 'Career',
    color: '#4C6A73',
    isPinned: false,
    tags: ['interview', 'prep'],
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-n7',
    title: 'Aptitude Formulas',
    content: 'Speed = Distance / Time\nWork = Efficiency x Time\nCompound Interest = P(1 + r/n)^(nt)',
    folder: 'Study',
    color: '#A2B5A0',
    isPinned: false,
    tags: ['aptitude', 'math'],
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-n8',
    title: 'LifeOS Ideas',
    content: 'Planned features:\n- Pomodoro timer widget\n- Financial expense tracker\n- Interactive AI goal coach.',
    folder: 'Ideas',
    color: '#6B7F4E',
    isPinned: false,
    tags: ['lifeos', 'features'],
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-n9',
    title: 'Portfolio Ideas',
    content: 'Interactive showcase:\n- Live demo links\n- Embedded video walkthroughs\n- GitHub repository links.',
    folder: 'Ideas',
    color: '#DCC8A3',
    isPinned: false,
    tags: ['portfolio', 'design'],
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-n10',
    title: 'Git Commands',
    content: 'Useful git workflow:\n- git checkout -b feature-branch\n- git rebase -i main\n- git stash push -m "wip".',
    folder: 'Tech',
    color: '#1F3D2E',
    isPinned: false,
    tags: ['git', 'devtools'],
    createdAt: new Date(Date.now() - 86400000 * 9).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 9).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-n11',
    title: 'SQL Notes',
    content: 'Database Queries:\n- JOIN types (INNER, LEFT, RIGHT, FULL)\n- GROUP BY and HAVING clauses\n- Window functions (ROW_NUMBER, RANK).',
    folder: 'Study',
    color: '#5A443A',
    isPinned: false,
    tags: ['sql', 'database'],
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-n12',
    title: 'Career Goals',
    content: 'Target milestones:\n1. Master Full-Stack Development\n2. Build scalable web applications\n3. Contribute to open-source projects.',
    folder: 'Career',
    color: '#4C6A73',
    isPinned: false,
    tags: ['career', 'goals'],
    createdAt: new Date(Date.now() - 86400000 * 11).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 11).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-n13',
    title: 'Learning Resources',
    content: 'Books & Documentation:\n- Clean Code by Robert C. Martin\n- Designing Data-Intensive Applications\n- Official React & Next.js Docs.',
    folder: 'Study',
    color: '#A2B5A0',
    isPinned: false,
    tags: ['learning', 'books'],
    createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-n14',
    title: 'AI Ideas',
    content: 'AI Integration:\n- Natural language intent parsing\n- Instant local state mutation\n- Real-time productivity advice.',
    folder: 'Ideas',
    color: '#6B7F4E',
    isPinned: false,
    tags: ['ai', 'future'],
    createdAt: new Date(Date.now() - 86400000 * 13).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 13).toISOString(),
    isDemo: true,
  },
  {
    id: 'demo-n15',
    title: 'Weekly Planning',
    content: 'Focus areas for next week:\n- Finish LifeOS UI Polish\n- Practice 15 LeetCode problems\n- Complete resume review.',
    folder: 'Career',
    color: '#DCC8A3',
    isPinned: false,
    tags: ['planning', 'weekly'],
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    isDemo: true,
  },
];
